"$schema" = 'https://starship.rs/config-schema.json'

format = """$directory($git_branch$git_state$git_status) $character"""

[character]
success_symbol = '[󰄾](bold green) '
error_symbol = '[✗](bold red) '
